### ISSUE TITLE
Node2000 Error

### ISSUE THREAD

**Issue by RasitEvduzen** [synapticon/application_examples#1]
Hello everyone,
I've NODE2000 servo driver and I try to connection via demo_csp.py. But I've a problem and I dont fix it. I need help. I was control my motor & node 2000 using OBLAC Driver Box. Now I must control my device using python (Speed Control) via ethercat. Is there anybody can help me?

Here is my problem:

[DEBU] Init thread SUB Poll
[DEBU] Init thread DEALER Poll
[DEBU] Using address 127.0.0.1
[DEBU] Using message_timeout 0.01 seconds
[DEBU] Connected to tcp://127.0.0.1:62525
[DEBU] Connected to tcp://127.0.0.1:62524
[DEBU] Running thread SUB Poll
[DEBU] Running thread DEALER Poll
[WARN] The server will be pinged to keep the connection alive.
[DEBU] Retrieving the list of devices found on the network...
[DEBU] Stopping thread SUB Poll
[DEBU] Stopping thread DEALER Poll
[DEBU] Network disconnected
Traceback (most recent call last):
  File "demo_csp.py", line 114, in <module>
    raise e
  File "demo_csp.py", line 111, in <module>
    mmw.initialize_device_parameter_info_dict()
  File "/home/rasit/Desktop/Ethercat/application_examples-master/EtherCAT/motion_master/python/motion_master_wrapper.py", line 395, in initialize_device_parameter_info_dict
    message = obs.run()
  File "/home/rasit/.local/lib/python3.8/site-packages/rx/core/observable/observable.py", line 286, in run
    return run(self)
  File "/home/rasit/.local/lib/python3.8/site-packages/rx/core/run.py", line 62, in run
    raise exception  # pylint: disable=raising-bad-type
Exception: No response from Motion Master for message 'get device info'

**Comment by fjes** [comment]
Hello @RasitEvduzen , I'm sorry you have problem with your Node2000. Please contact support@synapticon.com with your problem. There we can help you with that issue. Thank you for your understanding.
